In [1]:
""" External Imports """
import maboss
import pandas as pd
import matplotlib.pyplot as plt
import sys
import numpy as np
sys.path.append("/Users/emilieyu/endotehelial-masboss")

ipylab module is not installed, menus and toolbar are disabled.

In [2]:
from src.config import load_sim_config, load_sweep_config
from src.paths import *
from boolean_models.scripts import *

In [3]:
sim_cfg = load_sim_config()
sweep_cfg = load_sweep_config()

MODELS_BND = DATA_DIR / sim_cfg['model']['bnd_v2']
MODELS_CFG = DATA_DIR / sim_cfg['model']['cfg_v4']

In [4]:
""" Setup base model. """
base_model = maboss.load(str(MODELS_BND), str(MODELS_CFG))
base_model.param['max_time'] = 10.0
base_model.param['sample_count'] = 5000

## Run Perturbations and Parameter Sweeps

In [6]:
perb_full_df, ss_df = run_perturbations(base_model, sim_cfg)
ss_df

DEBUG: Running perturbation: WT
DEBUG: Running perturbation: DSP_KO
DEBUG: Running perturbation: TJP1_KO
DEBUG: Running perturbation: JCAD_KO
DEBUG: Running perturbation: DSP_JCAD_DKO
DEBUG: Running perturbation: TJP1_JCAD_DKO
DEBUG: All simulations completed successfully

,t,DSP,TJP1,JCAD,RhoA,RhoC,perturbation,delta,phenotype
0,9.9,0.000000,0.661295,0.000000,0.378205,0.600772,DSP_JCAD_DKO,0.222567,Normal
1,9.9,0.000000,0.661048,0.662283,0.251231,0.795533,DSP_KO,0.544302,Hyper
2,9.9,0.668700,0.667842,0.000000,0.523592,0.514232,JCAD_KO,-0.009360,Normal
3,9.9,0.670368,0.000000,0.000000,0.613813,0.364588,TJP1_JCAD_DKO,-0.249225,Normal
4,9.9,0.670409,0.000000,0.668916,0.805174,0.263563,TJP1_KO,-0.541611,Failed
5,9.9,0.673050,0.678001,0.666478,0.641849,0.647216,WT,0.005367,Normal

In [7]:
perb_full_df[perb_full_df['perturbation'] == 'DSP_KO']

,t,DSP,TJP1,JCAD,RhoA,RhoC,perturbation,delta,phenotype
100,0.0,0.0,0.514226,0.501792,0.480802,0.540472,DSP_KO,0.059670,Normal
101,0.1,0.0,0.533480,0.529835,0.439276,0.577077,DSP_KO,0.137801,Normal
102,0.2,0.0,0.548431,0.553320,0.411529,0.598250,DSP_KO,0.186721,Normal
103,0.3,0.0,0.567669,0.573883,0.392933,0.619097,DSP_KO,0.226164,Normal
104,0.4,0.0,0.585875,0.587684,0.377390,0.639372,DSP_KO,0.261982,Hyper
...,...,...,...,...,...,...,...,...,...
195,9.5,0.0,0.665066,0.664002,0.249143,0.798495,DSP_KO,0.549352,Hyper
196,9.6,0.0,0.666688,0.663990,0.248656,0.796984,DSP_KO,0.548328,Hyper
197,9.7,0.0,0.666717,0.665825,0.254614,0.797122,DSP_KO,0.542508,Hyper
198,9.8,0.0,0.665251,0.666997,0.253387,0.798341,DSP_KO,0.544954,Hyper
199,9.9,0.0,0.663825,0.667325,0.247365,0.798756,DSP_KO,0.551391,Hyper

In [8]:
sweep_recruitment = run_sweeps(base_model, sweep_cfg, sim_cfg, target_exp="Recruitment_Sweep", result_dir=None)
sweep_recruitment

>>> DEBUG: Initialising: Recruitment_Sweep (1D)
DEBUG: Starting Recruitment_Sweep sweep for perturbation: WT with ['$DSP_recruitment', '$TJP1_recruitment', '$JCAD_recruitment']
DEBUG: Completed Recruitment_Sweep sweep for perturbation: WT
DEBUG: Combined parameter sweep experiment data saved to None

,DSP,JCAD,RhoA,RhoC,TJP1,p1_name,p1_value,p2_name,p2_value,perturbation,exp_name,type,delta,phenotype
9.9000,0.514801,0.672544,0.526074,0.681767,0.667903,$DSP_recruitment,0.00,NaN,NaN,WT,Recruitment_Sweep,1D,0.155693,Normal
9.9000,0.579686,0.662550,0.547083,0.683824,0.672096,$DSP_recruitment,0.05,NaN,NaN,WT,Recruitment_Sweep,1D,0.136741,Normal
9.9000,0.628718,0.654393,0.575426,0.666969,0.665769,$DSP_recruitment,0.10,NaN,NaN,WT,Recruitment_Sweep,1D,0.091543,Normal
9.9000,0.658057,0.665526,0.598268,0.667243,0.669260,$DSP_recruitment,0.15,NaN,NaN,WT,Recruitment_Sweep,1D,0.068975,Normal
9.9000,0.664262,0.662669,0.606174,0.650815,0.669329,$DSP_recruitment,0.20,NaN,NaN,WT,Recruitment_Sweep,1D,0.044641,Normal
9.9000,0.664122,0.675252,0.602839,0.659675,0.668231,$DSP_recruitment,0.25,NaN,NaN,WT,Recruitment_Sweep,1D,0.056836,Normal
9.9000,0.653171,0.673553,0.611275,0.654181,0.666117,$DSP_recruitment,0.30,NaN,NaN,WT,Recruitment_Sweep,1D,0.042906,Normal
9.9000,0.666876,0.662500,0.626138,0.648261,0.669586,$DSP_recruitment,0.35,NaN,NaN,WT,Recruitment_Sweep,1D,0.022123,Normal
9.9000,0.665839,0.660445,0.616655,0.649318,0.659138,$DSP_recruitment,0.40,NaN,NaN,WT,Recruitment_Sweep,1D,0.032663,Normal
9.9000,0.671900,0.668563,0.629034,0.637993,0.663257,$DSP_recruitment,0.45,NaN,NaN,WT,Recruitment_Sweep,1D,0.008959,Normal
9.9000,0.668665,0.663921,0.631944,0.641701,0.650917,$DSP_recruitment,0.50,NaN,NaN,WT,Recruitment_Sweep,1D,0.009757,Normal
9.9000,0.670029,0.660170,0.615258,0.653495,0.665375,$DSP_recruitment,0.55,NaN,NaN,WT,Recruitment_Sweep,1D,0.038237,Normal
9.9000,0.661940,0.663180,0.625035,0.645254,0.674691,$DSP_recruitment,0.60,NaN,NaN,WT,Recruitment_Sweep,1D,0.020219,Normal
9.9000,0.664647,0.662253,0.630994,0.643438,0.668506,$DSP_recruitment,0.65,NaN,NaN,WT,Recruitment_Sweep,1D,0.012444,Normal
9.9000,0.673751,0.663349,0.636099,0.637897,0.654653,$DSP_recruitment,0.70,NaN,NaN,WT,Recruitment_Sweep,1D,0.001798,Normal
9.9000,0.661156,0.674841,0.632801,0.625374,0.656393,$DSP_recruitment,0.75,NaN,NaN,WT,Recruitment_Sweep,1D,-0.007427,Normal
9.9000,0.661199,0.663156,0.624939,0.651515,0.665796,$DSP_recruitment,0.80,NaN,NaN,WT,Recruitment_Sweep,1D,0.026576,Normal
9.9000,0.666359,0.669406,0.629802,0.659441,0.677434,$DSP_recruitment,0.85,NaN,NaN,WT,Recruitment_Sweep,1D,0.029639,Normal
9.9000,0.666229,0.659748,0.641957,0.634846,0.659089,$DSP_recruitment,0.90,NaN,NaN,WT,Recruitment_Sweep,1D,-0.007111,Normal
9.9000,0.658159,0.677471,0.639906,0.640639,0.653102,$DSP_recruitment,0.95,NaN,NaN,WT,Recruitment_Sweep,1D,0.000733,Normal
9.9000,0.682945,0.665622,0.699193,0.524383,0.513400,$TJP1_recruitment,0.00,NaN,NaN,WT,Recruitment_Sweep,1D,-0.174810,Normal
9.9000,0.658159,0.665417,0.678557,0.561578,0.580148,$TJP1_recruitment,0.05,NaN,NaN,WT,Recruitment_Sweep,1D,-0.116979,Normal
9.9000,0.674538,0.667888,0.666342,0.583925,0.628359,$TJP1_recruitment,0.10,NaN,NaN,WT,Recruitment_Sweep,1D,-0.082417,Normal
9.9000,0.671688,0.674323,0.657720,0.601749,0.643250,$TJP1_recruitment,0.15,NaN,NaN,WT,Recruitment_Sweep,1D,-0.055971,Normal
9.9000,0.662493,0.665406,0.655228,0.603481,0.661289,$TJP1_recruitment,0.20,NaN,NaN,WT,Recruitment_Sweep,1D,-0.051747,Normal
9.9000,0.663078,0.666165,0.655651,0.615700,0.668681,$TJP1_recruitment,0.25,NaN,NaN,WT,Recruitment_Sweep,1D,-0.039951,Normal
9.9000,0.665286,0.652235,0.654554,0.608158,0.663536,$TJP1_recruitment,0.30,NaN,NaN,WT,Recruitment_Sweep,1D,-0.046396,Normal
9.9000,0.675394,0.675051,0.656390,0.619245,0.658833,$TJP1_recruitment,0.35,NaN,NaN,WT,Recruitment_Sweep,1D,-0.037145,Normal
9.9000,0.657525,0.680342,0.647839,0.629424,0.667160,$TJP1_recruitment,0.40,NaN,NaN,WT,Recruitment_Sweep,1D,-0.018415,Normal
9.9000,0.671643,0.658682,0.649608,0.625799,0.665898,$TJP1_recruitment,0.45,NaN,NaN,WT,Recruitment_Sweep,1D,-0.023809,Normal
9.9000,0.673454,0.667572,0.644367,0.637647,0.664182,$TJP1_recruitment,0.50,NaN,NaN,WT,Recruitment_Sweep,1D,-0.006720,Normal
9.9000,0.671058,0.676714,0.646810,0.620294,0.667254,$TJP1_recruitment,0.55,NaN,NaN,WT,Recruitment_Sweep,1D,-0.026516,Normal
9.9000,0.674345,0.664138,0.634379,0.634152,0.663404,$TJP1_recruitment,0.60,NaN,NaN,WT,Recruitment_Sweep,1D,-0.000227,Normal
9.9000,0.667893,0.666302,0.638302,0.644624,0.677297,$TJP1_recruitment,0.65,NaN,NaN,WT,Recruitment_Sweep,1D,0.006322,Normal
9.9000,0.671986,0.670004,0.649541,0.629031,0.670809,$TJP1_recruitment,0.70,NaN,NaN,WT,Recruitment_Sweep,1D,-0.020510,Normal
9.9000,0.670120,0.674686,0.656435,0.637894,0.664786,$TJP1_recruitment,0.75,NaN,NaN,WT,Recruitment_Sweep,1D,-0.018541,Normal
9.9000,0.656527,0.661872,0.638419,0.625933,0.673314,$TJP1_recruitment,0.80,NaN,NaN,WT,Recruitment_Sweep,1D,-0.012486,Normal
9.9000,0.678569,0.670802,0.655685,0.628668,0.673623,$TJP1_recruitment,0.85,NaN,NaN,WT,Recruitment_Sweep,1D,-0.027017,Normal
9.9000,0.665070,0.676633,0.639660,0.647045,0.669786,$TJP1_recruitment,0.90,NaN,NaN,WT,Recruitment_Sweep,1D,0.007385,Normal
9.9000,0.668727,0.674294,0.646771,0.641103,0.652387,$TJP1_recruitment,0.95,NaN,NaN,WT,Recruitment_Sweep,1D,-0.005668,Normal
9.9000,0.660135,0.484798,0.614623,0.595771,0.663614,$JCAD_recruitment,0.00,NaN,NaN,WT,Recruitment_Sweep,1D,-0.018852,Normal
9.9000,0.671042,0.581386,0.618438,0.618764,0.653877,$JCAD_recruitment,0.05,NaN,NaN,WT,Recruitment_Sweep,1D,0.000326,Normal
9.9000,0.664561,0.627846,0.625457,0.634685,0.662001,$JCAD_recruitment,0.10,NaN,NaN,WT,Recruitment_Sweep,1D,0.009228,Normal
9.9000,0.676880,0.644255,0.646179,0.620622,0.662491,$JCAD_recruitment,0.15,NaN,NaN,WT,Recruitment_Sweep,1D,-0.025557,Normal
9.9000,0.668385,0.639522,0.634902,0.628118,0.665209,$JCAD_recruitment,0.20,NaN,NaN,WT,Recruitment_Sweep,1D,-0.006784,Normal
9.9000,0.666389,0.653111,0.626949,0.634284,0.674302,$JCAD_recruitment,0.25,NaN,NaN,WT,Recruitment_Sweep,1D,0.007335,Normal
9.9000,0.670917,0.656170,0.639399,0.628055,0.670115,$JCAD_recruitment,0.30,NaN,NaN,WT,Recruitment_Sweep,1D,-0.011344,Normal
9.9000,0.661223,0.665401,0.648583,0.637819,0.670072,$JCAD_recruitment,0.35,NaN,NaN,WT,Recruitment_Sweep,1D,-0.010764,Normal
9.9000,0.672676,0.672031,0.646338,0.641333,0.673862,$JCAD_recruitment,0.40,NaN,NaN,WT,Recruitment_Sweep,1D,-0.005005,Normal
9.9000,0.667658,0.672271,0.634734,0.637096,0.675934,$JCAD_recruitment,0.45,NaN,NaN,WT,Recruitment_Sweep,1D,0.002362,Normal
9.9000,0.680219,0.665254,0.641613,0.628956,0.663300,$JCAD_recruitment,0.50,NaN,NaN,WT,Recruitment_Sweep,1D,-0.012657,Normal
9.9000,0.667436,0.653581,0.636586,0.634781,0.669394,$JCAD_recruitment,0.55,NaN,NaN,WT,Recruitment_Sweep,1D,-0.001805,Normal
9.9000,0.653553,0.668509,0.631915,0.637178,0.663574,$JCAD_recruitment,0.60,NaN,NaN,WT,Recruitment_Sweep,1D,0.005263,Normal
9.9000,0.680687,0.665021,0.647395,0.630472,0.660662,$JCAD_recruitment,0.65,NaN,NaN,WT,Recruitment_Sweep,1D,-0.016923,Normal
9.9000,0.672312,0.666291,0.641871,0.634119,0.666197,$JCAD_recruitment,0.70,NaN,NaN,WT,Recruitment_Sweep,1D,-0.007752,Normal
9.9000,0.658732,0.664464,0.635120,0.635577,0.660809,$JCAD_recruitment,0.75,NaN,NaN,WT,Recruitment_Sweep,1D,0.000457,Normal
9.9000,0.684493,0.674755,0.639746,0.652813,0.671394,$JCAD_recruitment,0.80,NaN,NaN,WT,Recruitment_Sweep,1D,0.013067,Normal
9.9000,0.672952,0.673725,0.637956,0.649694,0.667133,$JCAD_recruitment,0.85,NaN,NaN,WT,Recruitment_Sweep,1D,0.011738,Normal
9.9000,0.667706,0.652813,0.639862,0.637696,0.669331,$JCAD_recruitment,0.90,NaN,NaN,WT,Recruitment_Sweep,1D,-0.002166,Normal
9.9000,0.676632,0.669756,0.634781,0.646256,0.673173,$JCAD_recruitment,0.95,NaN,NaN,WT,Recruitment_Sweep,1D,0.011475,Normal

In [9]:
sweep_recruitment.dropna(axis=1)

,DSP,JCAD,RhoA,RhoC,TJP1,p1_name,p1_value,perturbation,exp_name,type,delta,phenotype
9.9000,0.514801,0.672544,0.526074,0.681767,0.667903,$DSP_recruitment,0.00,WT,Recruitment_Sweep,1D,0.155693,Normal
9.9000,0.579686,0.662550,0.547083,0.683824,0.672096,$DSP_recruitment,0.05,WT,Recruitment_Sweep,1D,0.136741,Normal
9.9000,0.628718,0.654393,0.575426,0.666969,0.665769,$DSP_recruitment,0.10,WT,Recruitment_Sweep,1D,0.091543,Normal
9.9000,0.658057,0.665526,0.598268,0.667243,0.669260,$DSP_recruitment,0.15,WT,Recruitment_Sweep,1D,0.068975,Normal
9.9000,0.664262,0.662669,0.606174,0.650815,0.669329,$DSP_recruitment,0.20,WT,Recruitment_Sweep,1D,0.044641,Normal
9.9000,0.664122,0.675252,0.602839,0.659675,0.668231,$DSP_recruitment,0.25,WT,Recruitment_Sweep,1D,0.056836,Normal
9.9000,0.653171,0.673553,0.611275,0.654181,0.666117,$DSP_recruitment,0.30,WT,Recruitment_Sweep,1D,0.042906,Normal
9.9000,0.666876,0.662500,0.626138,0.648261,0.669586,$DSP_recruitment,0.35,WT,Recruitment_Sweep,1D,0.022123,Normal
9.9000,0.665839,0.660445,0.616655,0.649318,0.659138,$DSP_recruitment,0.40,WT,Recruitment_Sweep,1D,0.032663,Normal
9.9000,0.671900,0.668563,0.629034,0.637993,0.663257,$DSP_recruitment,0.45,WT,Recruitment_Sweep,1D,0.008959,Normal
9.9000,0.668665,0.663921,0.631944,0.641701,0.650917,$DSP_recruitment,0.50,WT,Recruitment_Sweep,1D,0.009757,Normal
9.9000,0.670029,0.660170,0.615258,0.653495,0.665375,$DSP_recruitment,0.55,WT,Recruitment_Sweep,1D,0.038237,Normal
9.9000,0.661940,0.663180,0.625035,0.645254,0.674691,$DSP_recruitment,0.60,WT,Recruitment_Sweep,1D,0.020219,Normal
9.9000,0.664647,0.662253,0.630994,0.643438,0.668506,$DSP_recruitment,0.65,WT,Recruitment_Sweep,1D,0.012444,Normal
9.9000,0.673751,0.663349,0.636099,0.637897,0.654653,$DSP_recruitment,0.70,WT,Recruitment_Sweep,1D,0.001798,Normal
9.9000,0.661156,0.674841,0.632801,0.625374,0.656393,$DSP_recruitment,0.75,WT,Recruitment_Sweep,1D,-0.007427,Normal
9.9000,0.661199,0.663156,0.624939,0.651515,0.665796,$DSP_recruitment,0.80,WT,Recruitment_Sweep,1D,0.026576,Normal
9.9000,0.666359,0.669406,0.629802,0.659441,0.677434,$DSP_recruitment,0.85,WT,Recruitment_Sweep,1D,0.029639,Normal
9.9000,0.666229,0.659748,0.641957,0.634846,0.659089,$DSP_recruitment,0.90,WT,Recruitment_Sweep,1D,-0.007111,Normal
9.9000,0.658159,0.677471,0.639906,0.640639,0.653102,$DSP_recruitment,0.95,WT,Recruitment_Sweep,1D,0.000733,Normal
9.9000,0.682945,0.665622,0.699193,0.524383,0.513400,$TJP1_recruitment,0.00,WT,Recruitment_Sweep,1D,-0.174810,Normal
9.9000,0.658159,0.665417,0.678557,0.561578,0.580148,$TJP1_recruitment,0.05,WT,Recruitment_Sweep,1D,-0.116979,Normal
9.9000,0.674538,0.667888,0.666342,0.583925,0.628359,$TJP1_recruitment,0.10,WT,Recruitment_Sweep,1D,-0.082417,Normal
9.9000,0.671688,0.674323,0.657720,0.601749,0.643250,$TJP1_recruitment,0.15,WT,Recruitment_Sweep,1D,-0.055971,Normal
9.9000,0.662493,0.665406,0.655228,0.603481,0.661289,$TJP1_recruitment,0.20,WT,Recruitment_Sweep,1D,-0.051747,Normal
9.9000,0.663078,0.666165,0.655651,0.615700,0.668681,$TJP1_recruitment,0.25,WT,Recruitment_Sweep,1D,-0.039951,Normal
9.9000,0.665286,0.652235,0.654554,0.608158,0.663536,$TJP1_recruitment,0.30,WT,Recruitment_Sweep,1D,-0.046396,Normal
9.9000,0.675394,0.675051,0.656390,0.619245,0.658833,$TJP1_recruitment,0.35,WT,Recruitment_Sweep,1D,-0.037145,Normal
9.9000,0.657525,0.680342,0.647839,0.629424,0.667160,$TJP1_recruitment,0.40,WT,Recruitment_Sweep,1D,-0.018415,Normal
9.9000,0.671643,0.658682,0.649608,0.625799,0.665898,$TJP1_recruitment,0.45,WT,Recruitment_Sweep,1D,-0.023809,Normal
9.9000,0.673454,0.667572,0.644367,0.637647,0.664182,$TJP1_recruitment,0.50,WT,Recruitment_Sweep,1D,-0.006720,Normal
9.9000,0.671058,0.676714,0.646810,0.620294,0.667254,$TJP1_recruitment,0.55,WT,Recruitment_Sweep,1D,-0.026516,Normal
9.9000,0.674345,0.664138,0.634379,0.634152,0.663404,$TJP1_recruitment,0.60,WT,Recruitment_Sweep,1D,-0.000227,Normal
9.9000,0.667893,0.666302,0.638302,0.644624,0.677297,$TJP1_recruitment,0.65,WT,Recruitment_Sweep,1D,0.006322,Normal
9.9000,0.671986,0.670004,0.649541,0.629031,0.670809,$TJP1_recruitment,0.70,WT,Recruitment_Sweep,1D,-0.020510,Normal
9.9000,0.670120,0.674686,0.656435,0.637894,0.664786,$TJP1_recruitment,0.75,WT,Recruitment_Sweep,1D,-0.018541,Normal
9.9000,0.656527,0.661872,0.638419,0.625933,0.673314,$TJP1_recruitment,0.80,WT,Recruitment_Sweep,1D,-0.012486,Normal
9.9000,0.678569,0.670802,0.655685,0.628668,0.673623,$TJP1_recruitment,0.85,WT,Recruitment_Sweep,1D,-0.027017,Normal
9.9000,0.665070,0.676633,0.639660,0.647045,0.669786,$TJP1_recruitment,0.90,WT,Recruitment_Sweep,1D,0.007385,Normal
9.9000,0.668727,0.674294,0.646771,0.641103,0.652387,$TJP1_recruitment,0.95,WT,Recruitment_Sweep,1D,-0.005668,Normal
9.9000,0.660135,0.484798,0.614623,0.595771,0.663614,$JCAD_recruitment,0.00,WT,Recruitment_Sweep,1D,-0.018852,Normal
9.9000,0.671042,0.581386,0.618438,0.618764,0.653877,$JCAD_recruitment,0.05,WT,Recruitment_Sweep,1D,0.000326,Normal
9.9000,0.664561,0.627846,0.625457,0.634685,0.662001,$JCAD_recruitment,0.10,WT,Recruitment_Sweep,1D,0.009228,Normal
9.9000,0.676880,0.644255,0.646179,0.620622,0.662491,$JCAD_recruitment,0.15,WT,Recruitment_Sweep,1D,-0.025557,Normal
9.9000,0.668385,0.639522,0.634902,0.628118,0.665209,$JCAD_recruitment,0.20,WT,Recruitment_Sweep,1D,-0.006784,Normal
9.9000,0.666389,0.653111,0.626949,0.634284,0.674302,$JCAD_recruitment,0.25,WT,Recruitment_Sweep,1D,0.007335,Normal
9.9000,0.670917,0.656170,0.639399,0.628055,0.670115,$JCAD_recruitment,0.30,WT,Recruitment_Sweep,1D,-0.011344,Normal
9.9000,0.661223,0.665401,0.648583,0.637819,0.670072,$JCAD_recruitment,0.35,WT,Recruitment_Sweep,1D,-0.010764,Normal
9.9000,0.672676,0.672031,0.646338,0.641333,0.673862,$JCAD_recruitment,0.40,WT,Recruitment_Sweep,1D,-0.005005,Normal
9.9000,0.667658,0.672271,0.634734,0.637096,0.675934,$JCAD_recruitment,0.45,WT,Recruitment_Sweep,1D,0.002362,Normal
9.9000,0.680219,0.665254,0.641613,0.628956,0.663300,$JCAD_recruitment,0.50,WT,Recruitment_Sweep,1D,-0.012657,Normal
9.9000,0.667436,0.653581,0.636586,0.634781,0.669394,$JCAD_recruitment,0.55,WT,Recruitment_Sweep,1D,-0.001805,Normal
9.9000,0.653553,0.668509,0.631915,0.637178,0.663574,$JCAD_recruitment,0.60,WT,Recruitment_Sweep,1D,0.005263,Normal
9.9000,0.680687,0.665021,0.647395,0.630472,0.660662,$JCAD_recruitment,0.65,WT,Recruitment_Sweep,1D,-0.016923,Normal
9.9000,0.672312,0.666291,0.641871,0.634119,0.666197,$JCAD_recruitment,0.70,WT,Recruitment_Sweep,1D,-0.007752,Normal
9.9000,0.658732,0.664464,0.635120,0.635577,0.660809,$JCAD_recruitment,0.75,WT,Recruitment_Sweep,1D,0.000457,Normal
9.9000,0.684493,0.674755,0.639746,0.652813,0.671394,$JCAD_recruitment,0.80,WT,Recruitment_Sweep,1D,0.013067,Normal
9.9000,0.672952,0.673725,0.637956,0.649694,0.667133,$JCAD_recruitment,0.85,WT,Recruitment_Sweep,1D,0.011738,Normal
9.9000,0.667706,0.652813,0.639862,0.637696,0.669331,$JCAD_recruitment,0.90,WT,Recruitment_Sweep,1D,-0.002166,Normal
9.9000,0.676632,0.669756,0.634781,0.646256,0.673173,$JCAD_recruitment,0.95,WT,Recruitment_Sweep,1D,0.011475,Normal

In [10]:
sweep_1d = run_sweeps(base_model, sweep_cfg, sim_cfg, target_type='1D')

>>> DEBUG: Initialising: WT_Sweep (1D)
DEBUG: Starting WT_Sweep sweep for perturbation: WT with dict_keys(['$RhoA_amp', '$RhoA_mod', '$RhoA_basal', '$RhoA_antagonistic', '$RhoA_decay', '$RhoC_amp', '$RhoC_mod', '$RhoC_basal', '$RhoC_antagonistic', '$RhoC_decay'])
DEBUG: Completed WT_Sweep sweep for perturbation: WT

>>> DEBUG: Initialising: DSP_Sweep (1D)
DEBUG: Starting DSP_Sweep sweep for perturbation: DSP_KO with ['$RhoC_antagonistic', '$RhoC_mod', '$RhoC_amp', '$RhoC_decay']
DEBUG: Completed DSP_Sweep sweep for perturbation: DSP_KO

>>> DEBUG: Initialising: TJP1_Sweep (1D)
DEBUG: Starting TJP1_Sweep sweep for perturbation: TJP1_KO with ['$RhoA_antagonistic', '$RhoA_mod', '$RhoA_amp', '$RhoA_decay']
DEBUG: Completed TJP1_Sweep sweep for perturbation: TJP1_KO

>>> DEBUG: Initialising: JCAD_Sweep (1D)
DEBUG: Starting JCAD_Sweep sweep for perturbation: JCAD_KO with ['$RhoA_mod', '$RhoC_mod', '$RhoA_basal', '$RhoC_basal']
DEBUG: Completed JCAD_Sweep sweep for perturbation: JCAD_KO

>>> DEBUG: Initialising: DSP_JCAD_Sweep (1D)
DEBUG: Starting DSP_JCAD_Sweep sweep for perturbation: DSP_JCAD_DKO with ['$RhoC_mod', '$RhoC_basal', '$RhoA_basal']
DEBUG: Completed DSP_JCAD_Sweep sweep for perturbation: DSP_JCAD_DKO

>>> DEBUG: Initialising: TJP1_JCAD_Sweep (1D)
DEBUG: Starting TJP1_JCAD_Sweep sweep for perturbation: TJP1_JCAD_DKO with ['$RhoA_mod', '$RhoA_basal', '$RhoC_basal']
DEBUG: Completed TJP1_JCAD_Sweep sweep for perturbation: TJP1_JCAD_DKO

>>> DEBUG: Initialising: DSP_TJP1_Sweep (1D)
DEBUG: Starting DSP_TJP1_Sweep sweep for perturbation: DSP_TJP1_DKO with ['$RhoA_basal', '$RhoC_basal']
ERROR: Failed experiment DSP_TJP1_Sweep: 'DSP_TJP1_DKO'
DEBUG: Combined parameter sweep experiment data saved to None

In [15]:
sweep_1d

,DSP,JCAD,RhoA,RhoC,TJP1,p1_name,p1_value,p2_name,p2_value,perturbation,exp_name,type,delta,phenotype
9.9000,0.505201,0.506200,0.344931,0.626727,0.488000,$RhoA_amp,0.0,N/A,NaN,WT,WT_Sweep,1D,0.281796,Hyper
9.9000,0.501000,0.492201,0.494898,0.567507,0.499800,$RhoA_amp,2.5,N/A,NaN,WT,WT_Sweep,1D,0.072609,Normal
9.9000,0.497201,0.491400,0.528119,0.563373,0.502201,$RhoA_amp,5.0,N/A,NaN,WT,WT_Sweep,1D,0.035254,Normal
9.9000,0.493600,0.502799,0.541637,0.562828,0.500400,$RhoA_amp,7.5,N/A,NaN,WT,WT_Sweep,1D,0.021191,Normal
9.9000,0.506802,0.495000,0.552135,0.549716,0.494602,$RhoA_amp,10.0,N/A,NaN,WT,WT_Sweep,1D,-0.002419,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9.9000,0.496800,NaN,0.555410,0.420602,NaN,$RhoC_basal,0.6,N/A,NaN,TJP1_JCAD_DKO,TJP1_JCAD_Sweep,1D,-0.134808,Normal
9.9000,0.505800,NaN,0.533125,0.488441,NaN,$RhoC_basal,0.8,N/A,NaN,TJP1_JCAD_DKO,TJP1_JCAD_Sweep,1D,-0.044684,Normal
9.9000,0.499400,NaN,0.492281,0.544280,NaN,$RhoC_basal,1.0,N/A,NaN,TJP1_JCAD_DKO,TJP1_JCAD_Sweep,1D,0.051999,Normal
9.9000,0.503401,NaN,0.468640,0.582252,NaN,$RhoC_basal,1.2,N/A,NaN,TJP1_JCAD_DKO,TJP1_JCAD_Sweep,1D,0.113612,Normal
9.9000,0.506400,NaN,0.453891,0.617342,NaN,$RhoC_basal,1.4,N/A,NaN,TJP1_JCAD_DKO,TJP1_JCAD_Sweep,1D,0.163451,Normal